spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/main?useUnicode=true&characterEncoding=utf-8
    username: admin  
    password: admin
  jpa:
    show-sql: true
    dialect: org.hibernate.dialect.MySQLInnoDBDialect

server:
  context-path: /redisdemo
  port: 80

environments:
  redis:
   host: 52.76.146.244
   port: 8000

logging:
  level:
    org.springframework.security: 'DEBUG'