spring:
  datasource:
    driverClassName: oracle.jdbc.OracleDriver
    url:  jdbc:oracle:thin:@//news.c2bsxwfs72wz.ap-southeast-1.rds.amazonaws.com:1521/ORCL
    username: root
    password: root1234
  jpa:
    show-sql: true
    dialect: org.hibernate.dialect.Oracle10gDialect

server:
  context-path: /redisdemo
  port: 9000

environments:
  redis:
   host: 52.76.146.244
   port: 8000